; Smart Locker - PlatformIO settings for VS Code
; Uses the same ESP32 Arduino version as the wokwi.com website (core 3.x)
[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =

  chris--a/Keypad
  madhephaestus/ESP32Servo
  adafruit/Adafruit GFX Library
  adafruit/Adafruit SSD1306
  miguelbalboa/MFRC522
